[package]
name = "nta"
version = "0.1.0"
edition = "2021"
authors = ["Roman A. Voronkin"]

[dependencies]
clap = {version = "^3.2", features = ["derive"]}
env_logger = {version = "^0.9"}
futures = {version = "^0.3"}
log = {version = "^0.4"}
regex = {version = "^1.6"}
thiserror = {version = "^1"}
tokio = {version = "^1.18", features = ["full"]}
walkdir = {version = "^2"}
